In [1]:
import numpy as np

In [2]:
p=np.load("../params.npy")

In [3]:
pc = np.load("../params_conc.npy")

In [5]:
p.shape, pc.shape

((101, 3), (10100, 3))

In [9]:
pc[::100]

array([[0.11351, 0.1841 , 1.7932 ],
       [0.07024, 0.2023 , 2.3075 ],
       [0.31244, 0.2118 , 2.6341 ],
       [0.30162, 0.2185 , 2.4198 ],
       [0.45988, 0.2237 , 1.7667 ],
       [0.19861, 0.2281 , 1.6872 ],
       [0.50723, 0.2383 , 2.7174 ],
       [0.15954, 0.2319 , 1.862  ],
       [0.29647, 0.2352 , 1.8176 ],
       [0.34337, 0.241  , 2.2256 ],
       [0.2558 , 0.2436 , 2.1436 ],
       [0.20183, 0.246  , 2.5535 ],
       [0.24013, 0.2482 , 2.3944 ],
       [0.31814, 0.2504 , 2.0882 ],
       [0.17701, 0.2524 , 2.0644 ],
       [0.13198, 0.2543 , 1.2886 ],
       [0.19228, 0.2562 , 2.2517 ],
       [0.15671, 0.2579 , 2.1356 ],
       [0.28661, 0.2629 , 1.8405 ],
       [0.35044, 0.2645 , 2.1676 ],
       [0.07778, 0.2597 , 2.4333 ],
       [0.14832, 0.2613 , 1.8724 ],
       [0.25177, 0.266  , 1.9571 ],
       [0.16817, 0.2675 , 1.9211 ],
       [0.39287, 0.2731 , 1.8925 ],
       [0.14556, 0.2689 , 2.1839 ],
       [0.12665, 0.2704 , 1.9658 ],
       [0.18608, 0.2717 , 2.

In [19]:
np.array(sorted(pc[::100], key=lambda x: x[0]))-p

array([[ 0.0000e+00,  0.0000e+00,  1.2477e+00],
       [-3.7290e-02,  8.1500e-02,  1.3709e+00],
       [ 2.5100e-03, -9.9400e-02,  8.6910e-01],
       [ 2.5100e-03,  1.3380e-01,  8.6680e-01],
       [ 2.5100e-03, -2.1360e-01,  1.3904e+00],
       [ 2.5100e-03,  1.2600e-01,  1.6652e+00],
       [ 2.5100e-03,  7.2000e-03,  6.3350e-01],
       [ 2.5200e-03, -7.5800e-02,  1.6505e+00],
       [ 2.5200e-03,  1.8600e-02,  1.5816e+00],
       [ 2.5200e-03, -2.5000e-03,  9.9100e-01],
       [ 2.5300e-03,  3.7400e-02,  1.2628e+00],
       [ 2.5300e-03, -2.0600e-02,  8.9980e-01],
       [ 2.5300e-03, -8.1000e-03,  1.4328e+00],
       [ 2.5400e-03,  3.1000e-02,  1.6823e+00],
       [ 2.5500e-03,  4.3500e-02,  1.5213e+00],
       [ 2.5500e-03, -5.8400e-02,  9.5130e-01],
       [ 1.9500e-03, -6.0000e-04,  1.2941e+00],
       [ 0.0000e+00,  0.0000e+00,  1.2471e+00],
       [ 0.0000e+00,  0.0000e+00,  1.2151e+00],
       [ 0.0000e+00,  0.0000e+00,  1.1113e+00],
       [ 0.0000e+00,  0.0000e+00,  1.521

array([[0.     , 0.3    , 0.8523 ],
       [0.1    , 0.3    , 0.8295 ],
       [0.06271, 0.3815 , 1.0135 ],
       [0.06522, 0.2821 , 0.7563 ],
       [0.06773, 0.4159 , 0.9171 ],
       [0.07024, 0.2023 , 0.6231 ],
       [0.07275, 0.3283 , 0.9324 ],
       [0.07526, 0.3355 , 0.7828 ],
       [0.07778, 0.2597 , 0.8008 ],
       [0.0803 , 0.2783 , 0.8382 ],
       [0.08282, 0.2758 , 0.7285 ],
       [0.08535, 0.3132 , 0.8378 ],
       [0.08788, 0.2926 , 0.7429 ],
       [0.09041, 0.2845 , 0.8126 ],
       [0.09295, 0.3155 , 0.9411 ],
       [0.0955 , 0.359  , 1.0231 ],
       [0.09805, 0.3006 , 0.8059 ],
       [0.10061, 0.2796 , 0.769  ],
       [0.10318, 0.3977 , 1.0456 ],
       [0.10575, 0.3051 , 0.8004 ],
       [0.10833, 0.2833 , 0.8385 ],
       [0.11092, 0.3763 , 0.9574 ],
       [0.11351, 0.1841 , 0.4885 ],
       [0.11612, 0.3085 , 0.7821 ],
       [0.11874, 0.3143 , 0.8358 ],
       [0.12136, 0.3457 , 0.8811 ],
       [0.124  , 0.3028 , 0.8714 ],
       [0.12665, 0.2704 , 0.